source      'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ATCarToon' do
  
  
  pod 'ATRefresh_Swift',:git => 'https://github.com/tianya2416/ATRefresh_Swift.git'
  pod 'ATKit_Swift',    :git => 'https://github.com/tianya2416/ATKit_Swift.git'
  pod 'Kingfisher'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Moya'
  pod 'Hue'


  pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'KLRecycleScrollView'
  pod 'VTMagic','~> 1.2.4'
  pod 'FMDB'
  pod 'YNPageViewController'
  pod 'SDCycleScrollView'
end

